# Generated by Django 4.2.14 on 2024-07-17 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=100)),
                ('imei', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('renter_name', models.CharField(max_length=100)),
                ('mountly_limit', models.IntegerField()),
                ('oil_change', models.IntegerField()),
                ('financial', models.IntegerField()),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('leased', 'Leased'), ('repair', 'In Repair')], default='ready', max_length=20)),
                ('car_rented_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
