# Generated by Django 4.2.14 on 2024-07-17 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autopulse_app', '0004_alter_car_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='user',
        ),
    ]
