# Generated by Django 4.2.14 on 2024-07-18 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('autopulse_app', '0011_remove_car_user_alter_car_car_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='car_image',
            field=models.ImageField(default=1, upload_to='car_images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='imei',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='vin',
            field=models.CharField(max_length=17),
        ),
    ]
