# Generated by Django 4.2.14 on 2024-07-18 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('autopulse_app', '0012_car_user_alter_car_car_image_alter_car_imei_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='final_odometer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='imei',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='renter_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='car',
            name='vin',
            field=models.CharField(max_length=100),
        ),
    ]
