# Generated by Django 4.2.14 on 2024-07-18 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autopulse_app', '0013_alter_car_final_odometer_alter_car_imei_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
